version: '3'
services:
  nodenv:
    build: .
    ports:
    - "49160:8081"
    volumes:
    - .:/usr/src/app
    depends_on:
      - mongo
    command: "npm install && npm install -g grunt-cli  && npm start"
  mongo:
    image: "mongo:3.2-jessie"
